<?php

namespace Vanni\ConfigManager\Services;

use Vanni\ConfigManager\Models\ConfigProject;
use Vanni\ConfigManager\Models\ConfigEnvironment;

class EnvExporter
{
    /**
     * Genera il contenuto di un file .env
     * per un progetto e un ambiente specifico.
     */
    public function generate(
        ConfigProject $project,
        ConfigEnvironment $environment
    ): string {
        $lines = [];

        $lines[] = '# Generated by Config Manager';
        $lines[] = '# Project: ' . $project->name;
        $lines[] = '# Environment: ' . $environment->name;
        $lines[] = '# Generated at: ' . now()->toDateTimeString();
        $lines[] = '';

        $variables = $project->variables()->with([
            'values' => function ($query) use ($environment) {
                $query->where('config_environment_id', $environment->id);
            }
        ])->get();

        foreach ($variables as $variable) {
            $value = optional($variable->values->first())->value;

            if ($value === null) {
                $lines[] = '# ' . $variable->key . '=';
            } else {
                $lines[] = $variable->key . '=' . $this->escapeValue($value);
            }
        }

        $lines[] = '';

        return implode(PHP_EOL, $lines);
    }

    /**
     * Scrive il file .env.config-manager
     */
    public function writeToFile(string $content): void
    {
        $path = base_path('.env.config-manager');

        file_put_contents($path, $content);
    }

    /**
     * Format a value so that it is safe inside a .env file.
     */
    protected function escapeValue(string $value): string
    {
        // Quote if the value contains characters that can break .env parsing
        $needsQuotes =
            str_contains($value, "\n") ||   // multiline
            str_contains($value, "\r") ||   // Windows newlines
            str_contains($value, ' ')  ||
            str_contains($value, '#')  ||
            str_contains($value, '=')  ||
            str_contains($value, '"');

        // Escape internal double quotes
        $escaped = str_replace('"', '\"', $value);

        return $needsQuotes
            ? '"' . $escaped . '"'
            : $escaped;
    }
}
